apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cert
  namespace: istio-ingress
spec:
  dnsNames:
    - argo.jack-newbury.co.uk
  secretName: argo-cert-tls
  issuerRef:
    name: jack-newbury-selfsigned
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-https-gateway
  namespace: argocd
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "argo-cert-tls"
      hosts:
        - "argocd.jack-newbury.co.uk"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-https
  namespace: argocd
spec:
  hosts:
    - "argocd.jack-newbury.co.uk"
  gateways:
    - argocd-https-gateway
  http:
    - match:
        - uri:
            prefix: /

      route:
        - destination:
            host: argocd-server
            port:
              number: 443
