apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "longhorn.jack-newbury.co.uk"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: longhorn
spec:
  hosts:
    - "longhorn.jack-newbury.co.uk"
  gateways:
    - http-gateway
  http:
    - match:
        - uri:
            prefix: /

      route:
        - destination:
            host: longhorn-frontend
            port:
              number: 80
