apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: istio-ingress
spec:
  dnsNames:
    - longhorn.jack-newbury.co.uk
  secretName: longhorn-cert-tls
  issuerRef:
    name: jack-newbury-selfsigned
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
  namespace: longhorn-system
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "longhorn-cert-tls"
      hosts:
        - "longhorn.jack-newbury.co.uk"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  hosts:
    - "longhorn.jack-newbury.co.uk"
  gateways:
    - http-gateway
  http:
    - match:
        - uri:
            prefix: /

      route:
        - destination:
            host: longhorn-frontend
            port:
              number: 80
