apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-https-gateway
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "grafana-cert"
      hosts:
        - "grafana.jack-newbury.co.uk"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-https
spec:
  hosts:
    - "grafana.jack-newbury.co.uk"
  gateways:
    - grafana-https-gateway
  tls:
    - match:
        - sniHosts:
            - "grafana.jack-newbury.co.uk"
      route:
        - destination:
            host: grafana
            port:
              number: 80
